[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "smartbuild"
version = "0.0.1"
description = "SmartBuild demo package"
readme = "README.md"
requires-python = ">=3.11"

[project.scripts]
smartbuild = "smartbuild.cli:main"
